Repository nst-sdc/DevCoin, pull requests merged in 2025-02, with the labels that each got.

#1 update ui background of website. Co-worker Vipul
  package-lock.json
  package.json
  src/App.tsx
  src/components/ChangePasswordModal.tsx
  src/components/EditProfileModal.tsx
  src/components/Footer.tsx
  src/components/MemberCard.tsx
  src/components/Navbar.tsx
  src/components/admin/AdminPanel.tsx
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/common/BackgroundLayout.tsx
  src/components/projects/ProjectCard.tsx
  src/pages/CoinsPage.tsx
  src/pages/HomePage.tsx
  src/pages/LeaderboardPage.tsx
  src/pages/MembersPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ProjectPage.tsx
  tailwind.config.js
Labels: enhancement, size:XL

#2 Added About page and added content in Home Page
  src/App.tsx
  src/components/Navbar.tsx
  src/pages/AboutPage.tsx
  src/pages/HomePage.tsx
Labels: enhancement, size:L

#3 Fix Issue of build and add recruitment page.
  src/components/Navbar.tsx
  src/pages/HomePage.tsx
  vite.config.ts
Labels: size:M
